// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Collections.Generic;
using System.Linq;
using Content.Shared._Shitmed.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Shitmed.UserInterface.Systems.Targeting.Widgets;

[GenerateTypedNameReferences]
public sealed partial class TargetingControl : UIWidget
{
    private readonly TargetingUIController _controller;
    private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;
    private static readonly ResPath RsiPath = new("/Textures/_Shitmed/Interface/Targeting/Doll/LifewebDoll.rsi");

    public TargetingControl()
    {
        RobustXamlLoader.Load(this);
        _controller = UserInterfaceManager.GetUIController<TargetingUIController>();

        _bodyPartControls = new Dictionary<TargetBodyPart, TextureButton>
        {
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Chest, ChestButton },
            { TargetBodyPart.Groin, GroinButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.LeftHand, LeftHandButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.RightHand, RightHandButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.LeftFoot, LeftFootButton },
            { TargetBodyPart.RightLeg, RightLegButton },
            { TargetBodyPart.RightFoot, RightFootButton },
        };

        var partStates = new Dictionary<TargetBodyPart, string>
        {
            { TargetBodyPart.Head, "head" },
            { TargetBodyPart.Chest, "chest" },
            { TargetBodyPart.Groin, "groin" },
            { TargetBodyPart.LeftArm, "l_arm" },
            { TargetBodyPart.LeftHand, "l_hand" },
            { TargetBodyPart.RightArm, "r_arm" },
            { TargetBodyPart.RightHand, "r_hand" },
            { TargetBodyPart.LeftLeg, "l_leg" },
            { TargetBodyPart.LeftFoot, "l_foot" },
            { TargetBodyPart.RightLeg, "r_leg" },
            { TargetBodyPart.RightFoot, "r_foot" }
        };

        foreach (var bodyPartButton in _bodyPartControls)
        {
            bodyPartButton.Value.MouseFilter = MouseFilterMode.Stop;
            bodyPartButton.Value.OnPressed += _ => SetActiveBodyPart(bodyPartButton.Key);

            if (bodyPartButton.Value.Children.First() is AnimatedTextureRect animRect)
            {
                animRect.SetFromSpriteSpecifier(new SpriteSpecifier.Rsi(RsiPath, partStates[bodyPartButton.Key]));
                animRect.DisplayRect.Stretch = TextureRect.StretchMode.KeepAspectCentered;
            }
        }

        TargetDoll.SetFromSpriteSpecifier(new SpriteSpecifier.Rsi(RsiPath, "zone_sel"));
        TargetDoll.DisplayRect.Stretch = TextureRect.StretchMode.KeepAspectCentered;
    }

    private void SetActiveBodyPart(TargetBodyPart bodyPart) => _controller.CycleTarget(bodyPart);

    public void SetBodyPartsVisible(TargetBodyPart bodyPart)
    {
        foreach (var bodyPartButton in _bodyPartControls)
            bodyPartButton.Value.Children.First().Visible = bodyPartButton.Key == bodyPart;
    }

    protected override void OnThemeUpdated()
    {
        // No longer relying on standard Theme target_doll texture, we use the animated RSI.
        // If theme updating is still needed for base logic, leave it here.
    }

    public void SetTargetDollVisible(bool visible) => Visible = visible;

}

